### ISSUE TITLE
Getting Authentication failure! invalid_credentials

### ISSUE THREAD

**Issue by dogweather** [linchus/omniauth-gitlab#10]
Here's the full error. I've been able to configure GitHub and Google devise/omniauth with problems.

```
E, [2016-02-12T10:54:55.373224 #15141] ERROR -- omniauth: (gitlab) Authentication failure! invalid_credentials: OAuth2::Error, invalid_grant: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
```

Any ideas?

**Comment by linchus** [comment]
I think it's a credentials issue.
Are you sure that it's correct?

**Comment by dogweather** [comment]
I'll recheck them - i copied & pasted from the gitlab.com screen.

**Comment by linchus** [comment]
Check also your redirect uri.
Probably, you run it at localhost, but at gitlab you set a production URI.

**Comment by dogweather** [comment]
Thanks, no, i've got them in sync, but localhost. I'm going to try a new production app config, see how that goes.

**Comment by dogweather** [comment]
Nope, very weird. Doesn't work in production either. Is this working for you with a recent version of devise?

**Comment by linchus** [comment]
I've got the same error.
It seems a doorkeeper issue, because it rejects access_token request which omniauth send. Omniauth adds GET parameters to callback_uri and doorkeeper not accepts it.

I need some time to investigate the issue.

**Comment by dosire** [comment]
Thanks for looking into this @linchus 

Please let us know if it is a GitLab problem or if we should improve something.

**Comment by linchus** [comment]
@dogweather Please, try version 1.0.2
It should be ok )

**Comment by dogweather** [comment]
Excellent - thank you. I'll give it a shot.

**Comment by dogweather** [comment]
Works great! Thank you.

![screen shot 2016-02-13 at 5 39 26 pm](https://cloud.githubusercontent.com/assets/150670/13031191/c4f381f2-d278-11e5-879d-a59cb2e1cbea.png)
http://nonstop.qa/users/sign_in

Now, if we could just get this [GitLab Font-Awesome icon](https://github.com/FortAwesome/Font-Awesome/issues/1530) moving along, it'd be perfect. ;-)

**Comment by danilobytes** [comment]
I'm running into this issue if I set the scope to `openid` (`read_user` and `api` work fine). I've checked on GitLab settings and everything is matching what I set on my code.

```ruby
# omniauth.rb

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :gitlab, ENV['GITLAB_KEY'], ENV['GITLAB_SECRET'],
    client_options: {
      site: 'url'
    },
    scope: 'openid'
end
```

Log shows this error though:
```
E, [2018-01-12T15:23:46.075373 #5021] ERROR -- omniauth: (gitlab) Authentication failure! invalid_credentials: OAuth2::Error, insufficient_scope: The request requires higher privileges than provided by the access token.
{"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token.","scope":"read_user api"}
```

**Comment by linchus** [comment]
@danilobytes Gem performs request to gitlab api for user information in order to provide this info in  omniauth hash.
I think if you does not request this scope user information request will fail.

**Comment by dogweather** [comment]
@danilobytes Yep, I use `read_user`:

```ruby
      config.omniauth :gitlab,
                      ENV.fetch('OMNIAUTH_GITLAB_ID'),
                      ENV.fetch('OMNIAUTH_GITLAB_SECRET'),
                      scope: 'read_user'
```

Not sure why there'd even be an `openid` scope...
