### ISSUE TITLE
fix omniauth-oauth2 1.4.0 compatibility

### ISSUE THREAD

**Issue by pravi** [linchus/omniauth-gitlab#13]
see https://gitlab.com/gitlab-com/support-forum/issues/1270 for background discussion

**Comment by pravi** [comment]
This is how omniauth-google-oauth2 was fixed https://github.com/zquestz/omniauth-google-oauth2/pull/205

**Comment by linchus** [comment]
Thanks for report.
I'll add backward compatibility for omniauth-oauth2 soon.

**Comment by linchus** [comment]
I have tested omniauth-gitlab 1.0.2 with omniauth-oauth2 1.4.0 and it works with gitlab.com.

Could you provide more details?

**Comment by pravi** [comment]
It may then be a bug in how gitlab.com is using omniauth-gitlab, https://gitlab.com/gitlab-com/support-forum/issues/1270 has details.

**Comment by stanhu** [comment]
omniauth-gitlab 1.0.1 does not work, but 1.0.2 does. I believe this is a dupe of #10.

**Comment by pravi** [comment]
Updating to 1.0.2 fixed the issue.
