### ISSUE TITLE
Allow other scopes to work

### ISSUE THREAD

**Issue by danilobytes** [linchus/omniauth-gitlab#14]
Is it possible to use other GitLab's scopes with this gem? At the moment it seems to work only when using the `api` scope. If `read_user` and `openid` are chosen on GitLab end it doesn't work. They return the following message: `The requested scope is invalid, unknown, or malformed.`.

**Comment by linchus** [comment]
@danilobytes Yes, sure it is possible.

You should add scope param to provider configuration like this

```ruby
use OmniAuth::Builder do
  provider :gitlab, ENV['GITLAB_KEY'], ENV['GITLAB_SECRET'], scope: 'read_user openid'
end
```

I'll add it to readme. 
Thanks!
