### ISSUE TITLE
Version 1.0.3 is not backwards compatible with 1.0.2 configuration (Gitlab error invalid_credentials)

### ISSUE THREAD

**Issue by jornvandebeek** [linchus/omniauth-gitlab#17]
Under version 1.0.2 configuring omniauth with your Gitlab instance domain name was sufficient:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :gitlab, ENV['GITLAB_APPLICATION_ID'], ENV['GITLAB_SECRET'],
           client_options: { site: 'https://example.com' }
end
```

Under version 1.0.3 it requires the api path to be specified. 

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :gitlab, ENV['GITLAB_APPLICATION_ID'], ENV['GITLAB_SECRET'],
           client_options: { site: 'https://example.com/api/v4' }
end
```

Otherwise, trying to log in through Gitlab will fail with an invalid_credentials error from Gitlab.

This change was unexpected for a tiny version bump.

**Comment by linchus** [comment]
Sorry, my failt.

Return backward compatible in 1.0.4 for 1.0.x versions and release 2.0.0.

Thanks!
