### ISSUE TITLE
Add OAuth2 support

### ISSUE THREAD

**Issue by StephenOTT** [linchus/omniauth-gitlab#5]
Would it be possible to get a few usage examples in the readme?

**Comment by StephenOTT** [comment]
Also, this omniauth flow does not use the Application Authorization oauth flow correct?

**Comment by linchus** [comment]
Gitlab hasn't support OAuth flow yet. They will support OAuth2 since 7.7.0.

I'll add oauth2 support soon

**Comment by StephenOTT** [comment]
Hi.  Ya just saw that :).  I started a another omniauth strategy based on the github version.  But ya sooner the better.  7.7 releases today :)

**Comment by linchus** [comment]
Your MR are welcome )

**Comment by axilleas** [comment]
Hi, sorry for the hijack, I just stumbled upon this gem!

I pushed an OAuth2 strategy here a week ago: https://gitlab.com/gitlab-org/omniauth-gitlab

Any help is more than welcome :)

**Comment by StephenOTT** [comment]
@axilleas Thank you!  I assume this is not pushed to rubygems?

**Comment by StephenOTT** [comment]
@linchus would you be willing to yank your omniauth-gitlab gem from ruby gems, and we can replace it with @axilleas' gem?

**Comment by axilleas** [comment]
no, not pushed to rubygems yet. The one in gitlab.com still needs some love before it goes live. I'll try to add tests in the next couple of days. It would be cool if we managed to merge our efforts :)

**Comment by axilleas** [comment]
I have created https://gitlab.com/axil/omniauth2-gitlab and pushed to rubygems. I wanted to use it with a [Discourse omniauth plugin](https://gitlab.com/gitlab-org/discourse-omniauth-gitlab), until we come to a conclusion about the naming.

**Comment by StephenOTT** [comment]
@axilleas great!  I am going to put this through it paces while i merge the GitHub-Time-Tracking app into GitLab and hopefully we can get this sucker wrapped up: http://feedback.gitlab.com/forums/176466-general/suggestions/4161532-add-time-tracking-for-issues-similar-to-feng-offic

**Comment by StephenOTT** [comment]
@axilleas works like a charm!! Thanks

**Comment by linchus** [comment]
I've switched omniauth-gitlab gem to OAuth2 flow and released new major version.

```ruby
gem 'omniauth-gitlab', '>=1.0.0'
```
Enjoy.
