### ISSUE TITLE
Got message 'redirect uri included is not valid

### ISSUE THREAD

**Issue by setiawand** [linchus/omniauth-gitlab#7]
please help,
i tried setup gollum with omniauth-gitlab, but i got redirect uri included is not valid message on page

thanks

**Comment by linchus** [comment]
Please, show me your gitlab-auth config and git lab application settings

**Comment by setiawand** [comment]
actually it's just fixed, sergey :) 
so in gitlab config need to have the exact same uri with the one that omniauth redirected 
i got this url called when calling gollum page 

http://localhost/oauth/authorize?client_id=cd4636c1e79078779c18e0270c223aa60378a1fa7212cfd2b0983b4b75f3fd2b&redirect_uri=http%3A%2F%2Flocalhost%3A4567%2F__omnigollum__%2Fauth%2Fgitlab%2Fcallback&response_type=code&state=74a1f7935e3a6f7201c953fb2ad336449ca091841c370126

then i set it on gitlab oauth2 apps
redirect uri = http://localhost:4567/__omnigollum__/auth/gitlab/callback

and then, bingo it works :)

so that is in my local pc, but on my work server, i just can't put http as redirect uri on oauth apps, required https ;(

you have a clue?

thanks a lot

**Comment by linchus** [comment]
I think it's a doorkeeper issue.
For security reason you can't use http schema for production
